// src/screens/styles/SettingsMotorSafetyScreen.styles.ts
import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F4F7F6' },
  header: { paddingHorizontal: 20, paddingBottom: 24, borderBottomLeftRadius: 24, borderBottomRightRadius: 24 },
  backButton: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  backIcon: { fontSize: 18, color: '#FFFFFF', marginRight: 8 },
  backText: { fontSize: 14, color: '#FFFFFF', fontWeight: '500' },
  mainTitle: { fontSize: 22, fontWeight: '700', color: '#FFFFFF', marginBottom: 4 },
  subtitle: { fontSize: 14, color: 'rgba(255,255,255,0.65)' },
  content: { padding: 16, gap: 16 },
  infoBanner: { flexDirection: 'row', backgroundColor: '#E8F3F0', borderRadius: 16, padding: 12, gap: 12, alignItems: 'center' },
  infoIcon: { fontSize: 20 },
  infoText: { flex: 1, fontSize: 12, color: '#1F7A63' },
  section: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 16, shadowColor: '#1F7A63', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 2 },
  sectionTitle: { fontSize: 12, fontWeight: '600', color: '#8aabb3', letterSpacing: 0.5, marginBottom: 16, paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: '#f0f4f3' },
  sliderGroup: { gap: 20 },
  sliderItem: { gap: 4 },
  sliderLabel: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  sliderLabelText: { fontSize: 14, color: '#1a2e28' },
  sliderValue: { fontSize: 14, fontWeight: '600', color: '#1F7A63', backgroundColor: '#E8F3F0', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 8 },
  sliderTrack: { height: 6, backgroundColor: '#E8F3F0', borderRadius: 3, position: 'relative' },
  sliderFill: { position: 'absolute', left: 0, top: 0, bottom: 0, borderRadius: 3 },
  sliderThumb: { position: 'absolute', width: 16, height: 16, borderRadius: 8, backgroundColor: '#FFFFFF', top: -5, marginLeft: -8, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 2, elevation: 2, borderWidth: 2, borderColor: '#1F7A63' },
  sliderLimits: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 2 },
  limitText: { fontSize: 11, color: '#b0c8c2' },
  configSummary: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 16, shadowColor: '#1F7A63', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 1 },
  summaryTitle: { fontSize: 12, fontWeight: '600', color: '#8aabb3', letterSpacing: 0.5, marginBottom: 12 },
  summaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  summaryItem: { flex: 1, minWidth: '45%', backgroundColor: '#F4F7F6', borderRadius: 12, padding: 12 },
  summaryLabel: { fontSize: 11, color: '#8aabb3', marginBottom: 4 },
  summaryValue: { fontSize: 14, fontWeight: '600', color: '#1F7A63' },
  saveButton: { backgroundColor: '#1F7A63', paddingVertical: 16, borderRadius: 16, alignItems: 'center', marginTop: 8 },
  savedButton: { backgroundColor: '#6ED3B5' },
  saveButtonText: { fontSize: 14, fontWeight: '600', color: '#FFFFFF' },
});